[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = [
  'python -m pip install --upgrade pip',
  'cp main_simple.py main.py',
  'python -m pip install -r requirements-railway.txt'
]

[phases.build]
cmds = ['echo "Simple build complete"']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'